### ISSUE TITLE
Produce sensor PCBs

### ISSUE THREAD

**Issue by mcbottcher** [mcbottcher/ENG5220#10]
-PCB for accelerometer
-PCB for Microcontroller to interface sensors and PI

**Comment by danwareing1** [comment]
Have added links to some components (ADCs and voltage references to the drive)

**Comment by mcbottcher** [comment]
I will make a start on the wiki tonight, we can make a section to hold datasheets

**Comment by mcbottcher** [comment]
And an overall section for the hardware so other people can use our designs

**Comment by danwareing1** [comment]
PCB design for sensor board submitted
