### ISSUE TITLE
Look into Doxygen documentation

### ISSUE THREAD

**Issue by mcbottcher** [mcbottcher/ENG5220#14]

**Comment by jamielee183** [comment]
I'v done Doxygen before for Audio programming, it's pretty easy.

**Comment by mcbottcher** [comment]
Is it useful? Is it mostly used for describing classes?

**Comment by jamielee183** [comment]
Yeah, its not too much effort if you are doing it from the start. Can be used to describe methods and classes, their arguments and what not, ill send you an example of a real shitty one i made

**Comment by mcbottcher** [comment]
Awesome that would be great cheers
